### ISSUE TITLE
Auto generated batch error

### ISSUE THREAD

**Issue by cgpurbaugh** [sea-fire-europe-ltd/customizations#7]
```
Traceback (most recent call last):
  File "/home/virtual/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/virtual/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/__init__.py", line 1027, in call
    return fn(*args, **newargs)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 848, in submit
    self._submit()
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 837, in _submit
    self.save()
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 296, in _save
    self.run_before_save_methods()
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 879, in run_before_save_methods
    self.run_method("validate")
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 68, in validate
    self.make_batches('t_warehouse')
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 197, in make_batches
    reference_name=self.name)).insert().name
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 217, in insert
    self.set_new_name()
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 378, in set_new_name
    set_new_name(self)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/stock/doctype/batch/batch.py", line 96, in autoname
    self.batch_id = self.get_name_from_naming_series()
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/stock/doctype/batch/batch.py", line 134, in get_name_from_naming_series
    key = _make_naming_series_key(naming_series_prefix)
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/stock/doctype/batch/batch.py", line 63, in _make_naming_series_key
    if not unicode(prefix):
NameError: name 'unicode' is not defined
```

**Comment by agritheory** [comment]
fixed via c019bd4 and PR to erpnext
